version: '3.7'
services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    restart: on-failure
    volumes:
      - "./otel_config/otel-collector-config.yml:/etc/otelcol/otel-collector-config.yml"
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/log:/var/log:ro
    ports:
      - '4317:4317'
      - '4318:4318'
  clickhouse:
    image: clickhouse/clickhouse-server:22.7
    restart: on-failure
    environment:
      CLICKHOUSE_DB: uptrace
    healthcheck:
      test: ['CMD', 'wget', '--spider', '-q', 'localhost:8123/ping']
      interval: 1s
      timeout: 1s
      retries: 30
    ports:
      - '8123:8123'
      - '9000:9000'
  uptrace:
    image: 'uptrace/uptrace:1.3.1'
    restart: on-failure
    volumes:
      - ./otel_config/uptrace.yml:/etc/uptrace/uptrace.yml
      - uptrace_data:/var/lib/uptrace
    ports:
      - '14317:14317'
      - '14318:14318'
    depends_on:
      clickhouse:
        condition: service_healthy
  redis:
    image: 'redis:7-alpine'
    command:
      - redis-server
      - --save
      - '60'
      - '1'
      - --loglevel
      - warning
    restart: on-failure
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

volumes:
  redis_data:
    driver: local
  uptrace_data:
    driver: local
